version: '3.8'

networks:
  syneban:

services:
  database:
    container_name: database
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - syneban
  php:
    container_name: php
    build:
      context: ./symfony
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
        - APP_SECRET=${SYMFONY_APP_SECRET}
        - JWT_PASSPHRASE=${SYMFONY_JWT_PASSPHRASE}
    entrypoint: ["bash", "-c", "sleep 10; \"/entrypoint.sh\"; apache2-foreground"]
    depends_on:
      - database
    networks:
      - syneban
  next:
    container_name: next
    build:
      context: ./next
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - NEXT_PUBLIC_GOOGLE_LOGIN_URI=${GOOGLE_LOGIN_URI}
        - NEXT_PUBLIC_SITE_URL=${SITE_URL}
        - API_HOST=${API_HOST}
    depends_on:
      - php
    ports:
      - 80:3000
    networks:
      - syneban