name: Symfony Test

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./symfony

jobs:
  test:
    name: PHPUnit
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run tests
        run: php bin/phpunit
        env:
          DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_db
